name: Bump version for static assets and deploy static content to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check for uppercase letters in the dictionary
        run: |
          echo "Looking for uppercase letters in dictionary.txt..."
          if grep '[A-Z]' "static/dictionary.txt"; then
            echo "Error: Uppercase letters found"
            exit 1
          else
            echo "Success: No uppercase letters found"
          fi

  bump-static-files-version:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.push.outputs.commit_sha }}
    steps:
      - uses: actions/checkout@v4
      - id: bump_version
        run: |
          export PREVIOUS_VERSION="`cat .version`"
          export NEW_VERSION="`git rev-parse --short HEAD`"
          
          find ./static/ -type f -exec sed -i "s/_slakje_version=${PREVIOUS_VERSION}/_slakje_version=${NEW_VERSION}/g" {} +
          
          echo -n $NEW_VERSION > .version
      - id: push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[skip ci] bump static files version"
          git push
          echo "commit_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  deployment:
    needs: bump-static-files-version
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://perfectum.slakje.nl
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-static-files-version.outputs.commit_sha }}
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'static'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
